�M�W<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:2656;s:11:"post_author";s:2:"48";s:9:"post_date";s:19:"2015-07-14 12:24:09";s:13:"post_date_gmt";s:19:"2015-07-14 12:24:09";s:12:"post_content";s:8302:"<h1 style="text-align: left;">Your burning questions</h1>
Each month we will be answering your burning questions and offering tangible ways for you to make a real difference.

<strong>When you know more, you are encouraged to do more.</strong>
<h3>JUNE 2016</h3>
<strong>The US near-complete ban on the ivory trade: is it near enough?</strong>

In July 2013, we welcomed a commitment from President Obama to dramatically intensify the United States’ efforts to combat wildlife trafficking. He issued an executive order (the “Order”) which sought to address the billions of dollars’ worth of illicit revenue generated by wildlife trafficking.

The Order instructed executive departments and agencies, including the U.S. Fish and Wildlife Service (“USFWS”), to take all appropriate actions to combat wildlife trafficking. This included robustly enforcing existing laws as well as revising those considered ‘weak, ineffective or obstructive’. In response to the Order, this month the USFWS published a final rule (the “Rule”) revising section 4(d) of the Endangered Species Act 1973 (“ESA”), which will take effect on 6 July 2016. The Rule is described as a ‘near-complete ban on trade in elephant ivory’.<img class="wp-image-2680 alignright" src="http://iworry.org/wp-content/uploads/2015/07/a2.jpg" alt="a" width="528" height="320" />

As elephant advocates, our natural reaction may be, <em>but why not a ‘complete’ ban</em>? The USFWS maintain that the Rule strikes a balance to allow certain narrow exceptions, and that a total ban would restrict the movement of ivory for law enforcement measures, legitimate scientific purposes, and museum specimens.

Existing rules allow trade within the United States provided ivory has been lawfully imported prior to 1990 (when the African elephant first appeared on Appendix 1 of the Convention on International Trade in Endangered Species (“CITES”)) or, if the elephant died naturally and the trader has documentation to prove this. The inadequacy of this protection is clear. So too is the ease in which organised poaching criminals have been able to flood clean markets with dirty yields for so long.

The Rule will mean that inter-state commerce will only be possible if the antiques exemption criteria are met, or if such items contain a <em>de minimis</em> amount of ivory. To qualify for the antiques exemption, the item must be over 100 years old and have been imported through specified antiques ports. The <em>de minimis </em>rule, which also applies to foreign commerce, exempts manufactured objects if such items were imported before 1990 (or if outside of the United States, then removed from the wild before 1976), the ivory is a fixed component of the object which does not account for more than 50% of the value of the object and the total weight of the ivory does not exceed 200 grams.<img class="wp-image-2275 alignright" src="http://iworry.org/wp-content/uploads/2015/02/s-1024x683.jpg" alt="s" width="533" height="355" />

The legal treatment of sport-hunted trophies will also change significantly. Currently, non-commercial hunting trophies are allowed, without limit, provided the individual has obtained a permit for trophies deriving from Appendix 1 elephant populations. The new Rule will not ban all ivory trophy imports, or even all trophies deriving from Appendix 1 elephants. However, it does limit the number of permitted sport-hunted trophies to two per hunter per year and make it compulsory to obtain a permit for all trophies, regardless of their Appendix listing.

Despite the federal change in the law, each state will also enact legislation to ban trade. New York, New Jersey and California, where the domestic trade of ivory is reported to be most rigorous, have gone further than the Rule and legislated to ban the trade of <em>all</em> ivory acquired after 1990, meaning only the trade of antique ivory will be permitted.

The United States, arguably the world’s second-largest market for trafficked ivory, have made a robust move to further protect elephants, to deplete demand and make it resolutely more difficult to launder ivory within the United States. But what of China?

China is unquestionably <em>the</em> largest global market for the illegal ivory trade, and in September 2015 made a joint commitment with the United States to end domestic ivory trading and de-commodify the substance.

China faces complications such as offering those involved in the legal ivory carving industry with viable alternatives. However, the momentum brought about by the Rule in the United States will increase pressure on China to commit to a timetable for imposing a ban of its own. In 2013, when the United States crushed six tonnes of ivory, China, not wishing to be outdone, crushed 6.1 tonnes. If this is anything to go by, China’s ban <em>should</em> be imminent.

&nbsp;

<strong>‘CONservation’: Swaziland set on selling again
</strong>

Last month we considered how the law failed to protect the <a href="http://iworry.org/legal-corner/">'stolen 18'</a> from a profiteering scheme in which wild elephants were captured in Swaziland and sent to U.S. zoos under the guise of ‘conservation’.<img class="wp-image-2527 alignright" src="http://iworry.org/wp-content/uploads/2015/05/a6.jpg" width="612" height="285" />

Now, regrettably, it seems this southern African nation is at it again. According to leaked papers, Swaziland has submitted a proposal to the Convention on International Trade in Endangered Species (CITES) to sell its stockpile of rhino horns, which it estimates could generate approximately $10 million on the Asian market. Swaziland claims that the money would be used to protect rhinos from poaching.

Whether species are best protected through limited trade or a total ban is a divisive debate and one which has been argued extensively in recent months. In April, Kenya made history by sending a stockpile of ivory belonging to 10,000 elephants up in flames. This unequivocal commitment to killing the trade demonstrates to an increasingly consumerist world that elephants are worth more alive than dead.
<h4 style="text-align: center;">Swaziland requires two thirds of the countries present at CITES to vote in favor</h4>
Swaziland and other opponents of this approach contend that the money generated from the legal sale of these tusks would better protect some of the world’s most threatened species. However, cloaking such an enterprise in ‘conservation’ does not adequately justify the fact that ivory and rhino horn in the market, whether illegal or legal, fuels demand and threatens elephants and rhinos, pushing them closer to extinction.<img class="wp-image-3405 alignright" src="http://iworry.org/wp-content/uploads/2015/07/Max-1024x682.jpg" alt="Max" width="479" height="319" />

Further, if a government is able to earn substantial revenue from confiscated ivory or rhino horn, there is a real danger that it provides temptation, if not incentive, to impose sub-standard punishments and allow poachers to continue in their business of destruction.

Whether Swaziland will be granted permission to sell its rhino horn stock will be decided at the 17th meeting of the Conference of the Parties to CITES (<a href="https://cites.org/cop17">CoP17</a>) in South Africa this September. In order for the sale to go ahead, Swaziland will need two thirds of the countries present at the Conference to vote in their favour. This would certainly be a dangerous precedent to set, and a retrograde step in the fight to save some of the world’s most iconic species.

Cautious optimism may be possible ahead of CoP17. Mounting global pressure to cut demand for ivory and rhino horn, together with the legal restrictions on buying horns, <em>should</em> prevent this latest venture from ever taking place.
<h3><strong>ANY QUESTIONS YOU WOULD LIKE ANSWERED TO FEATURE HERE? <a href="mailto:infouk@sheldrickwildlifetrust.org">EMAIL US</a>.</strong></h3>
<h4>Download the timeline by <em>iworry</em> outlining the developments of the trade in ivory over the past 40 years here in <a href="http://iworry.org/wp-content/uploads/2015/07/Timeline_Website.pdf" target="_blank">PDF format</a>.</h4>
&nbsp;";s:10:"post_title";s:12:"Legal corner";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:4:"open";s:13:"post_password";s:0:"";s:9:"post_name";s:8:"timeline";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2016-06-23 17:21:01";s:17:"post_modified_gmt";s:19:"2016-06-23 17:21:01";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:0;s:4:"guid";s:31:"http://iworry.org/?page_id=2656";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}